name: my_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.1.2
  fluttertoast: ^8.2.8
  cupertino_icons: ^1.0.6
  intl_phone_field: ^3.0.2
  firebase_core: ^3.2.0
  google_sign_in: ^6.2.1
  tcard: ^1.3.0
  cloud_firestore: ^5.2.1
  image_picker: ^1.1.2
  firebase_storage: ^12.2.0
  timeago: ^3.7.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.0   # <--- Add this here

flutter:
  uses-material-design: true

  assets:
    - lib/images/apple.png
    - lib/images/google.png
    - lib/images/fb.png
    - lib/images/logo.png
    - lib/images/he.jpg
    - lib/images/jar.jpg
    - lib/images/ca.jpg
    - lib/icons/COSPLAY.png
    - lib/icons/LOGO.png
    - lib/icons/MOBA.png
    - lib/icons/PUZZLE.png
    - lib/icons/GHOST.png
    - lib/icons/RPG.png
    - lib/icons/CASUAL.png
    - lib/icons/WHEEL.png
    - lib/icons/GACHA.png
    - lib/icons/FPS.png

flutter_launcher_icons:
  android: true        # Enable Android icon generation
  ios: true            # Enable iOS icon generation
  image_path: "lib/icons/LOGO.png"  # Path to your custom icon file
  remove_alpha_ios: true   # Removes alpha channel for iOS icons
